# Generated by Django 3.0.6 on 2020-06-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('watchat', models.CharField(max_length=60)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='bollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('watchat', models.CharField(max_length=60)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='hollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('watchat', models.CharField(max_length=60)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('ratings', models.FloatField()),
                ('watchat', models.CharField(max_length=60)),
                ('link', models.URLField()),
            ],
        ),
    ]
